/*
 * Meridian and acupuncture point data — all 361 points of the 14 principal
 * meridians. Coordinates are authored for the posed Xbot model (y up, feet at
 * y=0, head top ~1.80, facing +Z, arms at the sides with palms forward) and
 * are snapped to the actual mesh surface at load time, so they only need to
 * be near the right spot on the right side of the body.
 *
 * A meridian has either `path` (one polyline) or `branches` (several).
 * Entries are named points ({code, name, en, pos, desc}) or bare waypoints
 * ({pos}) used to shape the curve. Bilateral meridians are mirrored in x.
 */

const MERIDIANS = [
  {
    id: "LU",
    name: "Lung",
    fullName: "Lung Meridian of Hand Taiyin",
    element: "Metal",
    color: 0xf2f4f7,
    totalPoints: 11,
    bilateral: true,
    description:
      "Governs qi and respiration. It begins on the upper chest, runs along the front-inner arm and ends at the thumb. Its points are used for cough, asthma, sore throat, colds and disorders of the skin.",
    path: [
      { code: "LU-1", name: "Zhongfu", en: "Middle Palace", pos: [0.135, 1.40, 0.045],
        desc: "Front-mu (alarm) point of the Lung, below the outer end of the clavicle. Used for cough, asthma, fullness of the chest and pain in the chest and shoulder." },
      { code: "LU-2", name: "Yunmen", en: "Cloud Gate", pos: [0.14, 1.435, 0.04],
        desc: "In the hollow below the outer clavicle, above LU-1. Treats cough, asthma and shoulder pain." },
      { code: "LU-3", name: "Tianfu", en: "Celestial Storehouse", pos: [0.21, 1.28, -0.015],
        desc: "On the inner upper arm, on the biceps. A 'window of the sky' point: nosebleed, asthma and disorientation." },
      { code: "LU-4", name: "Xiabai", en: "Guarding White", pos: [0.222, 1.24, -0.015],
        desc: "On the biceps below LU-3. Treats cough, chest oppression and pain of the inner arm." },
      { code: "LU-5", name: "Chize", en: "Cubit Marsh", pos: [0.245, 1.17, -0.015],
        desc: "He-sea point on the elbow crease, at the radial side of the biceps tendon. Clears heat from the Lung: cough with yellow phlegm, sore throat, and elbow pain." },
      { code: "LU-6", name: "Kongzui", en: "Collection Hole", pos: [0.29, 1.03, -0.02],
        desc: "Xi-cleft point on the forearm. For acute conditions: coughing blood, acute cough and sore throat." },
      { code: "LU-7", name: "Lieque", en: "Broken Sequence", pos: [0.328, 0.928, -0.028],
        desc: "Luo-connecting point above the radial styloid, and command point of the head and nape. A key point for the common cold, headache and stiff neck; opens the Conception Vessel (Ren mai)." },
      { code: "LU-8", name: "Jingqu", en: "Channel Ditch", pos: [0.331, 0.912, -0.026],
        desc: "Jing-river point just above the wrist crease at the radial artery. Cough, sore throat and wrist pain." },
      { code: "LU-9", name: "Taiyuan", en: "Great Abyss", pos: [0.33, 0.902, -0.025],
        desc: "Yuan-source point at the radial end of the wrist crease, and influential point of the vessels and pulse. Tonifies Lung qi: chronic cough, weak voice, weak pulse, wrist pain." },
      { code: "LU-10", name: "Yuji", en: "Fish Border", pos: [0.36, 0.855, -0.015],
        desc: "Ying-spring point on the thenar eminence. Clears Lung heat, especially from the throat: acute sore throat and loss of voice." },
      { code: "LU-11", name: "Shaoshang", en: "Lesser Shang", pos: [0.413, 0.828, 0.005],
        desc: "Jing-well point at the radial corner of the thumbnail. Used (often with bleeding technique) for severe sore throat, high fever and restoring consciousness." }
    ]
  },
  {
    id: "LI",
    name: "Large Intestine",
    fullName: "Large Intestine Meridian of Hand Yangming",
    element: "Metal",
    color: 0x90a4ae,
    totalPoints: 20,
    bilateral: true,
    description:
      "Paired with the Lung. It runs from the index finger up the outer arm, over the shoulder and neck to end beside the nose. Its points treat disorders of the face, mouth and throat, fever, and problems of the intestines.",
    path: [
      { code: "LI-1", name: "Shangyang", en: "Metal Yang", pos: [0.402, 0.742, -0.025],
        desc: "Jing-well point at the radial corner of the index fingernail. Used for fever, sore throat, toothache and loss of consciousness." },
      { code: "LI-2", name: "Erjian", en: "Second Space", pos: [0.398, 0.765, -0.035],
        desc: "Ying-spring point at the base of the index finger. Clears heat: toothache, sore throat and nosebleed." },
      { code: "LI-3", name: "Sanjian", en: "Third Space", pos: [0.392, 0.786, -0.04],
        desc: "Shu-stream point behind the index knuckle. Toothache, sore throat and pain of the hand." },
      { code: "LI-4", name: "Hegu", en: "Joining Valley", pos: [0.37, 0.825, -0.055],
        desc: "Yuan-source point on the back of the hand between thumb and index, and command point of the face and mouth. One of the most used points of all: headache, toothache, common cold, and pain anywhere in the body. Contraindicated during pregnancy." },
      { code: "LI-5", name: "Yangxi", en: "Yang Ravine", pos: [0.347, 0.893, -0.055],
        desc: "In the 'anatomical snuffbox' at the radial wrist. Wrist pain, headache and toothache." },
      { code: "LI-6", name: "Pianli", en: "Veering Passage", pos: [0.327, 0.96, -0.06],
        desc: "Luo-connecting point on the radial forearm. Regulates the water passages: edema, and treats nosebleed and tinnitus." },
      { code: "LI-7", name: "Wenliu", en: "Warm Flow", pos: [0.318, 0.995, -0.06],
        desc: "Xi-cleft point on the forearm. Acute conditions: sore throat, borborygmus and abdominal pain." },
      { code: "LI-8", name: "Xialian", en: "Lower Ridge", pos: [0.302, 1.05, -0.055],
        desc: "On the radial forearm below LI-9. Abdominal pain and pain of the elbow and arm." },
      { code: "LI-9", name: "Shanglian", en: "Upper Ridge", pos: [0.298, 1.068, -0.055],
        desc: "On the radial forearm below the elbow. Numbness and pain of the arm and shoulder." },
      { code: "LI-10", name: "Shousanli", en: "Arm Three Miles", pos: [0.276, 1.125, -0.05],
        desc: "Two cun below the elbow crease. A strong local point for tennis elbow, arm pain and weakness; also supports digestion." },
      { code: "LI-11", name: "Quchi", en: "Pool at the Bend", pos: [0.25, 1.16, -0.04],
        desc: "He-sea point at the outer end of the elbow crease. A major point to clear heat: fever, hypertension, skin diseases and elbow pain." },
      { code: "LI-12", name: "Zhouliao", en: "Elbow Bone Hole", pos: [0.243, 1.19, -0.05],
        desc: "Above the outer elbow. Local point for elbow pain, numbness and contracture." },
      { code: "LI-13", name: "Shouwuli", en: "Arm Five Miles", pos: [0.232, 1.235, -0.04],
        desc: "On the outer upper arm above the elbow. Elbow and arm pain; classical caution against deep needling (artery)." },
      { code: "LI-14", name: "Binao", en: "Upper Arm", pos: [0.213, 1.32, -0.03],
        desc: "At the lower border of the deltoid. Shoulder and arm pain, and eye disorders." },
      { code: "LI-15", name: "Jianyu", en: "Shoulder Bone", pos: [0.20, 1.455, -0.03],
        desc: "In the depression at the front of the shoulder when the arm is raised. A principal local point for shoulder pain and restricted movement (frozen shoulder)." },
      { code: "LI-16", name: "Jugu", en: "Great Bone", pos: [0.13, 1.475, -0.03],
        desc: "Between the clavicle and the scapular spine. Shoulder pain and difficulty raising the arm." },
      { code: "LI-17", name: "Tianding", en: "Celestial Tripod", pos: [0.075, 1.50, 0.02],
        desc: "On the side of the neck. Sudden loss of voice, sore throat and goiter." },
      { code: "LI-18", name: "Futu", en: "Support the Prominence", pos: [0.07, 1.53, 0.035],
        desc: "On the side of the neck level with the Adam's apple. Cough, wheezing, sore throat and goiter." },
      { code: "LI-19", name: "Kouheliao", en: "Grain Bone Hole", pos: [0.02, 1.60, 0.10],
        desc: "Below the nostril, beside the philtrum. Nasal congestion, nosebleed and facial paralysis." },
      { code: "LI-20", name: "Yingxiang", en: "Welcome Fragrance", pos: [0.028, 1.615, 0.105],
        desc: "Beside the nostril. The main point for nasal congestion, rhinitis, sinusitis and loss of smell; also used for facial paralysis." }
    ]
  },
  {
    id: "ST",
    name: "Stomach",
    fullName: "Stomach Meridian of Foot Yangming",
    element: "Earth",
    color: 0xffd54f,
    totalPoints: 45,
    bilateral: true,
    description:
      "Runs from below the eye, over the jaw (with a branch up to the forehead), down the front of the chest and abdomen, and along the front of the leg to the second toe. Central to digestion; its points treat gastrointestinal disorders, facial problems and fatigue.",
    branches: [
      [
        { code: "ST-1", name: "Chengqi", en: "Container of Tears", pos: [0.031, 1.638, 0.10],
          desc: "Directly below the pupil, on the rim of the eye socket. A local point for eye disorders: redness, excessive tearing, night blindness and twitching eyelids." },
        { code: "ST-2", name: "Sibai", en: "Four Whites", pos: [0.033, 1.625, 0.10],
          desc: "In the infraorbital foramen below the eye. Eye disorders, facial pain and paralysis." },
        { code: "ST-3", name: "Juliao", en: "Great Bone Hole", pos: [0.038, 1.608, 0.095],
          desc: "Below the cheekbone, level with the nostril. Facial paralysis, toothache and cheek swelling." },
        { code: "ST-4", name: "Dicang", en: "Earth Granary", pos: [0.045, 1.592, 0.09],
          desc: "Beside the corner of the mouth. A major point for facial paralysis, drooling and mouth deviation." },
        { code: "ST-5", name: "Daying", en: "Great Welcome", pos: [0.063, 1.575, 0.07],
          desc: "On the lower jaw in front of the masseter, over the facial artery. Toothache, jaw swelling and facial paralysis." },
        { code: "ST-6", name: "Jiache", en: "Jaw Bone", pos: [0.077, 1.585, 0.06],
          desc: "On the belly of the masseter muscle. Treats jaw problems: TMJ pain, toothache of the lower jaw, jaw clenching and facial paralysis." },
        { code: "ST-7", name: "Xiaguan", en: "Below the Joint", pos: [0.09, 1.615, 0.04],
          desc: "In front of the ear below the zygomatic arch. TMJ disorders, ear problems and toothache." },
        { code: "ST-8", name: "Touwei", en: "Head Corner", pos: [0.085, 1.71, 0.06],
          desc: "At the corner of the forehead, near the hairline. Used for frontal and temporal headache, dizziness and eye pain." }
      ],
      [
        { code: "ST-9", name: "Renying", en: "Man's Welcome", pos: [0.035, 1.52, 0.055],
          desc: "Beside the Adam's apple, over the carotid. Regulates blood pressure; sore throat and goiter. Needle with care." },
        { code: "ST-10", name: "Shuitu", en: "Water Prominence", pos: [0.038, 1.49, 0.06],
          desc: "On the neck below ST-9. Sore throat, cough and wheezing." },
        { code: "ST-11", name: "Qishe", en: "Qi Abode", pos: [0.04, 1.46, 0.065],
          desc: "Above the inner clavicle. Sore throat, neck stiffness and wheezing." },
        { code: "ST-12", name: "Quepen", en: "Empty Basin", pos: [0.065, 1.445, 0.055],
          desc: "In the hollow above the middle of the clavicle. Cough, wheezing and pain of the supraclavicular region. Needle with care (apex of lung)." },
        { code: "ST-13", name: "Qihu", en: "Qi Door", pos: [0.075, 1.42, 0.05],
          desc: "Below the middle of the clavicle. Cough, wheezing and chest fullness." },
        { code: "ST-14", name: "Kufang", en: "Storeroom", pos: [0.08, 1.38, 0.07],
          desc: "In the 1st intercostal space on the chest. Cough and fullness of the chest." },
        { code: "ST-15", name: "Wuyi", en: "Room Screen", pos: [0.09, 1.335, 0.08],
          desc: "In the 2nd intercostal space. Cough, wheezing and breast pain." },
        { code: "ST-16", name: "Yingchuang", en: "Breast Window", pos: [0.095, 1.30, 0.085],
          desc: "In the 3rd intercostal space above the breast. Breast pain, cough and chest oppression." },
        { code: "ST-17", name: "Ruzhong", en: "Breast Center", pos: [0.09, 1.27, 0.088],
          desc: "The center of the nipple. A reference landmark only — needling and moxibustion are forbidden." },
        { code: "ST-18", name: "Rugen", en: "Breast Root", pos: [0.09, 1.235, 0.085],
          desc: "In the crease below the breast. Insufficient lactation, breast pain and cough." },
        { code: "ST-19", name: "Burong", en: "Not Contained", pos: [0.06, 1.17, 0.10],
          desc: "On the upper abdomen beside the midline. Epigastric pain, vomiting and poor appetite." },
        { code: "ST-20", name: "Chengman", en: "Supporting Fullness", pos: [0.06, 1.14, 0.105],
          desc: "On the upper abdomen. Epigastric distension, vomiting and poor digestion." },
        { code: "ST-21", name: "Liangmen", en: "Beam Gate", pos: [0.058, 1.11, 0.11],
          desc: "Four cun above the navel, two cun lateral. An important local point for epigastric pain, acid reflux and poor appetite." },
        { code: "ST-22", name: "Guanmen", en: "Pass Gate", pos: [0.055, 1.085, 0.112],
          desc: "On the middle abdomen. Abdominal distension, borborygmus and diarrhea." },
        { code: "ST-23", name: "Taiyi", en: "Supreme Unity", pos: [0.055, 1.06, 0.115],
          desc: "On the middle abdomen. Restlessness, mania and indigestion." },
        { code: "ST-24", name: "Huaroumen", en: "Slippery Flesh Gate", pos: [0.052, 1.048, 0.118],
          desc: "Just above the level of the navel. Vomiting, gastric pain and mental restlessness." },
        { code: "ST-25", name: "Tianshu", en: "Celestial Pivot", pos: [0.05, 1.035, 0.12],
          desc: "Front-mu (alarm) point of the Large Intestine, two cun beside the navel. A pivotal point for all intestinal disorders: diarrhea, constipation, abdominal pain and distension." },
        { code: "ST-26", name: "Wailing", en: "Outer Mound", pos: [0.05, 1.01, 0.118],
          desc: "Below the level of the navel. Abdominal pain and menstrual pain." },
        { code: "ST-27", name: "Daju", en: "Great Gigantic", pos: [0.05, 0.985, 0.112],
          desc: "On the lower abdomen. Lower abdominal distension, urinary difficulty and hernia." },
        { code: "ST-28", name: "Shuidao", en: "Water Passage", pos: [0.05, 0.96, 0.105],
          desc: "On the lower abdomen. Promotes urination; edema, urinary retention and menstrual disorders." },
        { code: "ST-29", name: "Guilai", en: "Return", pos: [0.05, 0.935, 0.095],
          desc: "On the lower abdomen near the groin. Menstrual disorders, amenorrhea and hernia." },
        { code: "ST-30", name: "Qichong", en: "Rushing Qi", pos: [0.05, 0.915, 0.085],
          desc: "At the groin over the femoral pulse, where the channel meets the Sea of Grain. Hernia, genital disorders; needle with care." },
        { code: "ST-31", name: "Biguan", en: "Thigh Joint", pos: [0.10, 0.90, 0.06],
          desc: "At the top of the thigh below the hip bone. Weakness and pain of the leg, hip pain." },
        { code: "ST-32", name: "Futu", en: "Crouching Rabbit", pos: [0.10, 0.72, 0.055],
          desc: "On the bulge of the thigh muscle. Weakness or pain of the leg and knee, beriberi." },
        { code: "ST-33", name: "Yinshi", en: "Yin Market", pos: [0.10, 0.63, 0.05],
          desc: "Three cun above the kneecap. Cold and pain of the knee and leg." },
        { code: "ST-34", name: "Liangqiu", en: "Beam Hill", pos: [0.10, 0.585, 0.05],
          desc: "Xi-cleft point two cun above the kneecap. Acute gastric pain, acute knee pain and breast pain." },
        { code: "ST-35", name: "Dubi", en: "Calf's Nose", pos: [0.10, 0.52, 0.05],
          desc: "In the hollow lateral to the patellar ligament ('eye of the knee'). Knee pain and stiffness." },
        { code: "ST-36", name: "Zusanli", en: "Leg Three Miles", pos: [0.10, 0.45, 0.045],
          desc: "He-sea point, four finger-widths below the kneecap. The master point of tonification: strengthens digestion, boosts energy and immunity, and is classically used for health preservation and longevity." },
        { code: "ST-37", name: "Shangjuxu", en: "Upper Great Void", pos: [0.10, 0.38, 0.04],
          desc: "Lower he-sea point of the Large Intestine, on the shin. Diarrhea, dysentery and abdominal pain." },
        { code: "ST-38", name: "Tiaokou", en: "Narrow Opening", pos: [0.10, 0.31, 0.035],
          desc: "At the midpoint of the shin. A famous distal point for frozen shoulder; also leg pain." },
        { code: "ST-40", name: "Fenglong", en: "Abundant Bulge", pos: [0.112, 0.31, 0.02],
          desc: "Luo-connecting point, one finger-width lateral to ST-38. The principal point for resolving phlegm in all its forms: productive cough, dizziness, heaviness and mental fog." },
        { code: "ST-39", name: "Xiajuxu", en: "Lower Great Void", pos: [0.10, 0.27, 0.03],
          desc: "Lower he-sea point of the Small Intestine, on the shin. Lower abdominal pain and leg weakness." },
        { code: "ST-41", name: "Jiexi", en: "Stream Divide", pos: [0.085, 0.10, 0.02],
          desc: "Jing-river point at the middle of the front ankle crease. Ankle pain, headache and clears Stomach heat." },
        { code: "ST-42", name: "Chongyang", en: "Rushing Yang", pos: [0.085, 0.045, 0.09],
          desc: "Yuan-source point at the high point of the foot, over the dorsal artery. Facial paralysis, foot weakness and gastric disorders." },
        { code: "ST-43", name: "Xiangu", en: "Sunken Valley", pos: [0.088, 0.035, 0.12],
          desc: "Shu-stream point between the 2nd and 3rd metatarsals. Facial and eye swelling, borborygmus and foot pain." },
        { code: "ST-44", name: "Neiting", en: "Inner Court", pos: [0.09, 0.03, 0.14],
          desc: "Ying-spring point between the 2nd and 3rd toes. Clears heat from the Stomach channel: toothache of the upper jaw, gum swelling, facial pain and burning digestive complaints." },
        { code: "ST-45", name: "Lidui", en: "Severe Mouth", pos: [0.095, 0.015, 0.175],
          desc: "Jing-well point at the lateral corner of the 2nd toenail. Dream-disturbed sleep, mania, facial swelling and toothache." }
      ]
    ]
  },
  {
    id: "SP",
    name: "Spleen",
    fullName: "Spleen Meridian of Foot Taiyin",
    element: "Earth",
    color: 0xc9973b,
    totalPoints: 21,
    bilateral: true,
    description:
      "Begins at the big toe and ascends the inner leg to the abdomen and side of the chest. Governs the transformation and transportation of food and fluids; its points treat digestive weakness, dampness, bleeding and gynecological disorders.",
    path: [
      { code: "SP-1", name: "Yinbai", en: "Hidden White", pos: [0.06, 0.015, 0.17],
        desc: "Jing-well point at the medial corner of the big toenail. Used (often with moxa) for bleeding disorders such as heavy menstruation, and for dream-disturbed sleep." },
      { code: "SP-2", name: "Dadu", en: "Great Metropolis", pos: [0.055, 0.02, 0.15],
        desc: "Ying-spring point on the inner big toe. Digestive heat, abdominal distension and febrile disease." },
      { code: "SP-3", name: "Taibai", en: "Supreme White", pos: [0.05, 0.028, 0.12],
        desc: "Yuan-source point on the inner side of the foot behind the big-toe joint. Strengthens the Spleen: poor digestion, loose stools, heaviness and lethargy." },
      { code: "SP-4", name: "Gongsun", en: "Grandfather Grandson", pos: [0.045, 0.04, 0.095],
        desc: "Luo-connecting point on the arch of the foot. Opens the Penetrating vessel (Chong mai): gastric pain, vomiting, menstrual disorders." },
      { code: "SP-5", name: "Shangqiu", en: "Shang Hill", pos: [0.048, 0.065, 0.03],
        desc: "Jing-river point below and in front of the inner ankle bone. Digestive weakness with dampness, and ankle pain." },
      { code: "SP-6", name: "Sanyinjiao", en: "Three Yin Intersection", pos: [0.048, 0.17, -0.01],
        desc: "Meeting point of the three leg yin meridians (Spleen, Liver, Kidney), four finger-widths above the inner ankle. Treats digestive, gynecological, urinary and sleep disorders. Contraindicated during pregnancy." },
      { code: "SP-7", name: "Lougu", en: "Leaking Valley", pos: [0.045, 0.24, -0.005],
        desc: "On the inner shin above SP-6. Abdominal distension, borborygmus and leg numbness." },
      { code: "SP-8", name: "Diji", en: "Earth Pivot", pos: [0.042, 0.36, 0.0],
        desc: "Xi-cleft point on the inner shin. Acute menstrual pain and abdominal pain." },
      { code: "SP-9", name: "Yinlingquan", en: "Yin Mound Spring", pos: [0.045, 0.50, 0.005],
        desc: "He-sea point below the inner knee. The main point for resolving dampness: edema, urinary difficulty, heaviness, and it also treats knee pain." },
      { code: "SP-10", name: "Xuehai", en: "Sea of Blood", pos: [0.05, 0.585, 0.03],
        desc: "On the bulge of the inner thigh above the knee. Regulates and cools the blood: irregular menstruation, itching and skin eruptions." },
      { code: "SP-11", name: "Jimen", en: "Winnowing Gate", pos: [0.055, 0.70, 0.03],
        desc: "On the inner thigh. Urinary difficulty and swelling of the groin." },
      { code: "SP-12", name: "Chongmen", en: "Rushing Gate", pos: [0.055, 0.925, 0.06],
        desc: "At the groin crease over the femoral artery. Abdominal pain, hernia and urinary difficulty." },
      { code: "SP-13", name: "Fushe", en: "Bowel Abode", pos: [0.06, 0.955, 0.07],
        desc: "On the lower abdomen above the groin. Abdominal pain and hernia." },
      { code: "SP-14", name: "Fujie", en: "Abdominal Knot", pos: [0.065, 1.00, 0.09],
        desc: "On the lower abdomen. Abdominal pain around the navel, diarrhea and constipation." },
      { code: "SP-15", name: "Daheng", en: "Great Horizontal", pos: [0.07, 1.035, 0.10],
        desc: "Four cun lateral to the navel. Constipation, diarrhea and abdominal pain — regulates the intestines." },
      { code: "SP-16", name: "Fuai", en: "Abdominal Lament", pos: [0.07, 1.11, 0.09],
        desc: "On the upper abdomen. Abdominal pain, indigestion and dysentery." },
      { code: "SP-17", name: "Shidou", en: "Food Hole", pos: [0.09, 1.20, 0.08],
        desc: "On the side of the chest in the 5th intercostal space. Chest and rib-side fullness." },
      { code: "SP-18", name: "Tianxi", en: "Celestial Stream", pos: [0.11, 1.245, 0.07],
        desc: "In the 4th intercostal space lateral to the breast. Chest pain, cough and insufficient lactation." },
      { code: "SP-19", name: "Xiongxiang", en: "Chest Village", pos: [0.115, 1.285, 0.06],
        desc: "In the 3rd intercostal space on the side of the chest. Chest and rib-side pain." },
      { code: "SP-20", name: "Zhourong", en: "All-Round Flourishing", pos: [0.12, 1.32, 0.05],
        desc: "In the 2nd intercostal space on the side of the chest. Cough and chest fullness." },
      { code: "SP-21", name: "Dabao", en: "Great Embrace", pos: [0.145, 1.22, 0.0],
        desc: "The great luo-connecting point of the Spleen, on the mid-axillary line. Used for pain of the whole body, chest and rib-side pain, and generalized weakness." }
    ]
  },
  {
    id: "HT",
    name: "Heart",
    fullName: "Heart Meridian of Hand Shaoyin",
    element: "Fire",
    color: 0xef5350,
    totalPoints: 9,
    bilateral: true,
    description:
      "Emerges at the armpit and runs along the inner-back edge of the arm to the little finger. The Heart governs the blood and houses the mind (shen); its points treat palpitations, insomnia, anxiety and chest pain.",
    path: [
      { code: "HT-1", name: "Jiquan", en: "Highest Spring", pos: [0.155, 1.37, -0.04],
        desc: "At the center of the armpit. Used for chest and heart pain, and locally for frozen shoulder and arm numbness." },
      { code: "HT-2", name: "Qingling", en: "Green Spirit", pos: [0.195, 1.25, -0.03],
        desc: "On the inner upper arm above the elbow. Pain of the shoulder, arm and rib-side." },
      { code: "HT-3", name: "Shaohai", en: "Lesser Sea", pos: [0.225, 1.165, -0.03],
        desc: "He-sea point at the inner end of the elbow crease. Calms the spirit and treats elbow pain, tremor and numbness of the arm." },
      { code: "HT-4", name: "Lingdao", en: "Spirit Path", pos: [0.308, 0.94, -0.038],
        desc: "Jing-river point above the wrist on the ulnar side. Sudden loss of voice, elbow and arm pain." },
      { code: "HT-5", name: "Tongli", en: "Connecting Li", pos: [0.31, 0.928, -0.038],
        desc: "Luo-connecting point one cun above the wrist crease. Speech disorders, sudden loss of voice, palpitations." },
      { code: "HT-6", name: "Yinxi", en: "Yin Cleft", pos: [0.312, 0.917, -0.038],
        desc: "Xi-cleft point half a cun above the wrist crease. Night sweats and acute heart pain." },
      { code: "HT-7", name: "Shenmen", en: "Spirit Gate", pos: [0.315, 0.906, -0.038],
        desc: "Yuan-source point at the ulnar end of the wrist crease. The primary point for calming the mind: insomnia, anxiety, palpitations and poor memory." },
      { code: "HT-8", name: "Shaofu", en: "Lesser Mansion", pos: [0.34, 0.80, -0.015],
        desc: "Ying-spring point on the palm between the 4th and 5th metacarpals. Palpitations, mouth ulcers and itching of the genitals." },
      { code: "HT-9", name: "Shaochong", en: "Lesser Rushing", pos: [0.335, 0.745, -0.04],
        desc: "Jing-well point at the radial corner of the little fingernail. Used in emergencies to restore consciousness, and for palpitations with acute heat." }
    ]
  },
  {
    id: "SI",
    name: "Small Intestine",
    fullName: "Small Intestine Meridian of Hand Taiyang",
    element: "Fire",
    color: 0xff8a65,
    totalPoints: 19,
    bilateral: true,
    description:
      "Runs from the little finger up the back of the arm, zigzags over the shoulder blade and ascends the neck to end in front of the ear. Its points treat pain of the neck, shoulder and scapula, and disorders of the ear.",
    path: [
      { code: "SI-1", name: "Shaoze", en: "Lesser Marsh", pos: [0.328, 0.74, -0.05],
        desc: "Jing-well point at the ulnar corner of the little fingernail. The classic point for insufficient lactation; also used for fever and sore throat." },
      { code: "SI-2", name: "Qiangu", en: "Front Valley", pos: [0.325, 0.77, -0.052],
        desc: "Ying-spring point at the base of the little finger. Clears heat: sore throat, and numbness of the fingers." },
      { code: "SI-3", name: "Houxi", en: "Back Ravine", pos: [0.32, 0.80, -0.055],
        desc: "Shu-stream point on the ulnar edge of the hand. Opens the Governing Vessel (Du mai): stiff neck, occipital headache, and pain along the spine." },
      { code: "SI-4", name: "Wangu", en: "Wrist Bone", pos: [0.318, 0.85, -0.058],
        desc: "Yuan-source point on the ulnar side of the wrist. Wrist pain, jaundice and febrile disease." },
      { code: "SI-5", name: "Yanggu", en: "Yang Valley", pos: [0.316, 0.895, -0.06],
        desc: "Jing-river point at the ulnar wrist crease. Wrist pain, neck swelling and tinnitus." },
      { code: "SI-6", name: "Yanglao", en: "Nourishing the Old", pos: [0.318, 0.915, -0.065],
        desc: "Xi-cleft point above the ulnar head. Blurred vision, and acute pain of the shoulder, arm and low back — a point for the elderly." },
      { code: "SI-7", name: "Zhizheng", en: "Branch of the Upright", pos: [0.29, 1.02, -0.065],
        desc: "Luo-connecting point on the back of the forearm. Neck stiffness, elbow pain and emotional agitation." },
      { code: "SI-8", name: "Xiaohai", en: "Small Sea", pos: [0.235, 1.16, -0.075],
        desc: "He-sea point between the tip of the elbow and the 'funny bone'. Treats pain along the ulnar side of the arm and elbow." },
      { code: "SI-9", name: "Jianzhen", en: "True Shoulder", pos: [0.175, 1.34, -0.085],
        desc: "Behind the shoulder joint above the armpit crease. Shoulder pain and restricted arm movement." },
      { code: "SI-10", name: "Naoshu", en: "Upper Arm Shu", pos: [0.18, 1.41, -0.09],
        desc: "Above the rear armpit crease, below the scapular spine. Shoulder pain and weakness of the arm." },
      { code: "SI-11", name: "Tianzong", en: "Celestial Gathering", pos: [0.13, 1.33, -0.095],
        desc: "In the center of the shoulder blade. A key point for scapular pain and shoulder problems, often very tender on pressure." },
      { code: "SI-12", name: "Bingfeng", en: "Grasping the Wind", pos: [0.125, 1.40, -0.08],
        desc: "Above the scapular spine. Shoulder and scapular pain, numbness of the arm." },
      { code: "SI-13", name: "Quyuan", en: "Crooked Wall", pos: [0.105, 1.425, -0.075],
        desc: "At the medial end of the scapular spine. Shoulder and scapular stiffness and pain." },
      { code: "SI-14", name: "Jianwaishu", en: "Outer Shoulder Shu", pos: [0.085, 1.44, -0.07],
        desc: "Three cun lateral to the 1st thoracic vertebra. Shoulder and back pain, neck stiffness." },
      { code: "SI-15", name: "Jianzhongshu", en: "Middle Shoulder Shu", pos: [0.06, 1.46, -0.065],
        desc: "Two cun lateral to the 7th cervical vertebra. Cough, shoulder and back pain." },
      { code: "SI-16", name: "Tianchuang", en: "Celestial Window", pos: [0.075, 1.53, -0.01],
        desc: "On the side of the neck behind the sternocleidomastoid. Tinnitus, deafness, sore throat and neck stiffness." },
      { code: "SI-17", name: "Tianrong", en: "Celestial Countenance", pos: [0.085, 1.565, 0.025],
        desc: "Behind the angle of the jaw. Sore throat, swelling of the neck and tinnitus." },
      { code: "SI-18", name: "Quanliao", en: "Cheek Bone Hole", pos: [0.082, 1.60, 0.06],
        desc: "Below the cheekbone. A major point for facial pain, trigeminal neuralgia, toothache and facial paralysis." },
      { code: "SI-19", name: "Tinggong", en: "Auditory Palace", pos: [0.10, 1.628, 0.02],
        desc: "In front of the ear, in the depression formed when the mouth is open. The principal local point for tinnitus, hearing loss and ear infections." }
    ]
  },
  {
    id: "BL",
    name: "Bladder",
    fullName: "Bladder Meridian of Foot Taiyang",
    element: "Water",
    color: 0x42a5f5,
    totalPoints: 67,
    bilateral: true,
    description:
      "The longest meridian: from the inner corner of the eye, over the head, down the entire back in two parallel lines — where the back-shu points connect to every organ — and down the back of the leg to the little toe. Treats back pain, urinary disorders and organ imbalances.",
    branches: [
      [
        { code: "BL-1", name: "Jingming", en: "Bright Eyes", pos: [0.025, 1.658, 0.098],
          desc: "At the inner corner of the eye. The foremost local point for eye disorders: blurred vision, redness, tearing and eye strain." },
        { code: "BL-2", name: "Zanzhu", en: "Gathered Bamboo", pos: [0.028, 1.68, 0.095],
          desc: "At the inner end of the eyebrow. Used for frontal headache, sinus pain, eye problems and hiccups." },
        { code: "BL-3", name: "Meichong", en: "Eyebrow Ascension", pos: [0.025, 1.74, 0.075],
          desc: "Above the inner eyebrow at the hairline. Headache, dizziness and nasal congestion." },
        { code: "BL-4", name: "Quchai", en: "Deviating Turn", pos: [0.04, 1.75, 0.06],
          desc: "On the forehead within the hairline. Headache, blurred vision and nasal congestion." },
        { code: "BL-5", name: "Wuchu", en: "Fifth Place", pos: [0.032, 1.775, 0.045],
          desc: "On the scalp above the forehead. Headache, dizziness and epilepsy." },
        { code: "BL-6", name: "Chengguang", en: "Receiving Light", pos: [0.032, 1.795, 0.01],
          desc: "On the top of the scalp. Headache, dizziness and nasal congestion." },
        { code: "BL-7", name: "Tongtian", en: "Reaching Heaven", pos: [0.032, 1.79, -0.03],
          desc: "On the vertex of the scalp. Headache, nasal congestion, loss of smell and nosebleed." },
        { code: "BL-8", name: "Luoque", en: "Declining Connection", pos: [0.032, 1.755, -0.065],
          desc: "On the back of the scalp. Dizziness, blurred vision and tinnitus." },
        { code: "BL-9", name: "Yuzhen", en: "Jade Pillow", pos: [0.03, 1.70, -0.09],
          desc: "On the occiput. Headache, eye pain and nasal congestion." },
        { code: "BL-10", name: "Tianzhu", en: "Celestial Pillar", pos: [0.03, 1.585, -0.075],
          desc: "On the nape, beside the trapezius muscle. Treats stiff neck, occipital headache, dizziness and visual disturbance from neck tension." },
        { code: "BL-11", name: "Dazhu", en: "Great Shuttle", pos: [0.035, 1.40, -0.085],
          desc: "Influential point of bone, beside the 1st thoracic vertebra. Neck stiffness, fever and bone disorders." },
        { code: "BL-12", name: "Fengmen", en: "Wind Gate", pos: [0.035, 1.36, -0.09],
          desc: "Beside the 2nd thoracic vertebra. Where wind enters: common cold, cough and neck stiffness (often with moxa or cupping)." },
        { code: "BL-13", name: "Feishu", en: "Lung Shu", pos: [0.035, 1.32, -0.095],
          desc: "Back-shu point of the Lung, beside the 3rd thoracic vertebra. Used for cough, asthma and all chronic respiratory disorders." },
        { code: "BL-14", name: "Jueyinshu", en: "Jueyin Shu", pos: [0.035, 1.29, -0.098],
          desc: "Back-shu point of the Pericardium. Palpitations, chest oppression and anxiety." },
        { code: "BL-15", name: "Xinshu", en: "Heart Shu", pos: [0.035, 1.26, -0.10],
          desc: "Back-shu point of the Heart, beside the 5th thoracic vertebra. Palpitations, insomnia, poor memory and emotional disorders." },
        { code: "BL-16", name: "Dushu", en: "Governor Shu", pos: [0.035, 1.23, -0.10],
          desc: "Back-shu point of the Governing Vessel. Heart pain, abdominal pain and itching." },
        { code: "BL-17", name: "Geshu", en: "Diaphragm Shu", pos: [0.035, 1.20, -0.105],
          desc: "Influential point of blood, beside the 7th thoracic vertebra. All blood disorders: anemia, bleeding, blood stasis; also hiccups and vomiting." },
        { code: "BL-18", name: "Ganshu", en: "Liver Shu", pos: [0.035, 1.16, -0.108],
          desc: "Back-shu point of the Liver. Eye disorders, jaundice, rib-side pain, irritability and depression." },
        { code: "BL-19", name: "Danshu", en: "Gallbladder Shu", pos: [0.035, 1.13, -0.11],
          desc: "Back-shu point of the Gallbladder. Jaundice, bitter taste in the mouth and rib-side pain." },
        { code: "BL-20", name: "Pishu", en: "Spleen Shu", pos: [0.035, 1.10, -0.112],
          desc: "Back-shu point of the Spleen. Strengthens digestion: poor appetite, loose stools, fatigue and edema." },
        { code: "BL-21", name: "Weishu", en: "Stomach Shu", pos: [0.035, 1.075, -0.113],
          desc: "Back-shu point of the Stomach. Epigastric pain, indigestion and poor appetite." },
        { code: "BL-22", name: "Sanjiaoshu", en: "Triple Energizer Shu", pos: [0.035, 1.06, -0.114],
          desc: "Back-shu point of the Triple Energizer. Regulates fluids: edema, urinary difficulty and abdominal distension." },
        { code: "BL-23", name: "Shenshu", en: "Kidney Shu", pos: [0.035, 1.05, -0.115],
          desc: "Back-shu point of the Kidney, beside the 2nd lumbar vertebra. A central point for low back pain, fatigue, and urinary and reproductive weakness." },
        { code: "BL-24", name: "Qihaishu", en: "Sea of Qi Shu", pos: [0.035, 1.02, -0.113],
          desc: "Beside the 3rd lumbar vertebra. Low back pain and irregular menstruation." },
        { code: "BL-25", name: "Dachangshu", en: "Large Intestine Shu", pos: [0.035, 1.00, -0.11],
          desc: "Back-shu point of the Large Intestine, beside the 4th lumbar vertebra. Low back pain, constipation and diarrhea." },
        { code: "BL-26", name: "Guanyuanshu", en: "Origin Pass Shu", pos: [0.035, 0.975, -0.108],
          desc: "Beside the 5th lumbar vertebra. Low back pain, abdominal distension and urinary difficulty." },
        { code: "BL-27", name: "Xiaochangshu", en: "Small Intestine Shu", pos: [0.03, 0.955, -0.105],
          desc: "Back-shu point of the Small Intestine, on the sacrum. Lower abdominal pain and urinary disorders." },
        { code: "BL-28", name: "Pangguangshu", en: "Bladder Shu", pos: [0.03, 0.935, -0.103],
          desc: "Back-shu point of the Bladder, on the sacrum. Urinary disorders, low back and sacral pain." },
        { code: "BL-29", name: "Zhonglushu", en: "Mid-Spine Shu", pos: [0.03, 0.915, -0.10],
          desc: "On the sacrum. Low back stiffness and pain, dysentery." },
        { code: "BL-30", name: "Baihuanshu", en: "White Ring Shu", pos: [0.03, 0.895, -0.098],
          desc: "On the lower sacrum. Low back pain, and urinary or genital disorders." },
        { code: "BL-31", name: "Shangliao", en: "Upper Bone Hole", pos: [0.02, 0.95, -0.10],
          desc: "In the 1st sacral foramen. Low back pain, and gynecological and urinary disorders." },
        { code: "BL-32", name: "Ciliao", en: "Second Bone Hole", pos: [0.02, 0.93, -0.10],
          desc: "In the 2nd sacral foramen. The most used sacral point: low back pain, menstrual pain and urinary disorders; also used during labor." },
        { code: "BL-33", name: "Zhongliao", en: "Middle Bone Hole", pos: [0.02, 0.91, -0.098],
          desc: "In the 3rd sacral foramen. Low back pain, urinary and menstrual disorders." },
        { code: "BL-34", name: "Xialiao", en: "Lower Bone Hole", pos: [0.02, 0.89, -0.096],
          desc: "In the 4th sacral foramen. Low back and sacral pain, lower abdominal pain." },
        { code: "BL-35", name: "Huiyang", en: "Meeting of Yang", pos: [0.02, 0.87, -0.095],
          desc: "Beside the tip of the coccyx. Hemorrhoids, diarrhea and genital disorders." },
        { code: "BL-36", name: "Chengfu", en: "Hold and Support", pos: [0.09, 0.83, -0.10],
          desc: "At the center of the gluteal crease. Sciatica, low back pain and hemorrhoids." },
        { code: "BL-37", name: "Yinmen", en: "Gate of Abundance", pos: [0.088, 0.68, -0.08],
          desc: "At the middle of the back of the thigh. Sciatica, low back pain and thigh pain." },
        { code: "BL-40", name: "Weizhong", en: "Bend Middle", pos: [0.082, 0.50, -0.045],
          desc: "He-sea point at the center of the crease behind the knee, and command point of the back. The classic distal point for acute and chronic low back pain; also treats knee problems." },
        { code: "BL-55", name: "Heyang", en: "Confluence of Yang", pos: [0.082, 0.44, -0.045],
          desc: "Below the knee crease between the heads of the calf muscle. Low back and leg pain." },
        { code: "BL-56", name: "Chengjin", en: "Sinew Support", pos: [0.082, 0.37, -0.05],
          desc: "In the belly of the calf muscle. Calf cramps and pain, hemorrhoids." },
        { code: "BL-57", name: "Chengshan", en: "Mountain Support", pos: [0.082, 0.30, -0.05],
          desc: "In the notch below the calf muscle. The main point for calf cramps; also classically used for hemorrhoids." },
        { code: "BL-58", name: "Feiyang", en: "Taking Flight", pos: [0.10, 0.24, -0.045],
          desc: "Luo-connecting point on the lower calf. Headache, dizziness, low back and leg pain." },
        { code: "BL-59", name: "Fuyang", en: "Instep Yang", pos: [0.10, 0.13, -0.05],
          desc: "Xi-cleft point of the Yang Motility vessel, above the outer ankle. Acute low back pain and ankle pain." },
        { code: "BL-60", name: "Kunlun", en: "Kunlun Mountains", pos: [0.105, 0.09, -0.05],
          desc: "Between the outer ankle bone and the Achilles tendon. Treats headache, stiff neck, back pain and ankle sprain. Contraindicated during pregnancy." },
        { code: "BL-61", name: "Pucan", en: "Servant's Respect", pos: [0.11, 0.05, -0.04],
          desc: "On the outer heel below BL-60. Heel pain and weakness of the foot." },
        { code: "BL-62", name: "Shenmai", en: "Extending Vessel", pos: [0.115, 0.06, -0.01],
          desc: "Below the outer ankle bone. Opens the Yang Motility vessel (Yang Qiao mai): insomnia, headache, low back pain and epilepsy." },
        { code: "BL-63", name: "Jinmen", en: "Golden Gate", pos: [0.115, 0.05, 0.02],
          desc: "Xi-cleft point on the outer foot in front of the heel. Acute headache, epilepsy and ankle pain." },
        { code: "BL-64", name: "Jinggu", en: "Capital Bone", pos: [0.115, 0.045, 0.05],
          desc: "Yuan-source point on the outer edge of the foot. Headache, neck stiffness and eye disorders." },
        { code: "BL-65", name: "Shugu", en: "Binding Bone", pos: [0.115, 0.04, 0.09],
          desc: "Shu-stream point behind the little-toe joint. Headache, neck stiffness and eye pain." },
        { code: "BL-66", name: "Zutonggu", en: "Foot Connecting Valley", pos: [0.115, 0.03, 0.12],
          desc: "Ying-spring point at the base of the little toe. Headache, neck stiffness and nosebleed." },
        { code: "BL-67", name: "Zhiyin", en: "Reaching Yin", pos: [0.115, 0.02, 0.15],
          desc: "Jing-well point at the lateral corner of the little toenail. Famous for turning a breech fetus (with moxibustion); also used for headache and eye pain." }
      ],
      [
        { code: "BL-41", name: "Fufen", en: "Attached Branch", pos: [0.06, 1.36, -0.085],
          desc: "On the outer line beside the 2nd thoracic vertebra. Shoulder, back and neck stiffness." },
        { code: "BL-42", name: "Pohu", en: "Door of the Corporeal Soul", pos: [0.06, 1.32, -0.09],
          desc: "Outer line, level with the Lung shu. Cough, asthma and shoulder-back pain; the Lung's spiritual aspect (po)." },
        { code: "BL-43", name: "Gaohuangshu", en: "Vital Region Shu", pos: [0.06, 1.29, -0.093],
          desc: "Outer line, level with the 4th thoracic vertebra. A famous point (often moxa) for chronic, deep-seated deficiency: exhaustion, chronic cough and poor memory." },
        { code: "BL-44", name: "Shentang", en: "Hall of the Spirit", pos: [0.06, 1.26, -0.095],
          desc: "Outer line, level with the Heart shu. Palpitations, insomnia and chest oppression; the Heart's spirit (shen)." },
        { code: "BL-45", name: "Yixi", en: "Sighing Sound", pos: [0.06, 1.23, -0.096],
          desc: "Outer line, level with the 6th thoracic vertebra. Cough, asthma and back pain." },
        { code: "BL-46", name: "Geguan", en: "Diaphragm Pass", pos: [0.06, 1.20, -0.10],
          desc: "Outer line, level with the diaphragm shu. Difficulty swallowing, hiccups and vomiting." },
        { code: "BL-47", name: "Hunmen", en: "Gate of the Ethereal Soul", pos: [0.06, 1.16, -0.103],
          desc: "Outer line, level with the Liver shu. Rib-side pain, depression and insomnia; the Liver's soul (hun)." },
        { code: "BL-48", name: "Yanggang", en: "Yang Headrope", pos: [0.06, 1.13, -0.105],
          desc: "Outer line, level with the Gallbladder shu. Jaundice, abdominal pain and diarrhea." },
        { code: "BL-49", name: "Yishe", en: "Abode of Thought", pos: [0.06, 1.10, -0.107],
          desc: "Outer line, level with the Spleen shu. Abdominal distension, poor appetite; the Spleen's intellect (yi)." },
        { code: "BL-50", name: "Weicang", en: "Stomach Granary", pos: [0.06, 1.075, -0.108],
          desc: "Outer line, level with the Stomach shu. Epigastric pain and abdominal distension." },
        { code: "BL-51", name: "Huangmen", en: "Vitals Gate", pos: [0.06, 1.06, -0.108],
          desc: "Outer line, level with the 1st lumbar vertebra. Abdominal pain and masses, constipation." },
        { code: "BL-52", name: "Zhishi", en: "Residence of the Will", pos: [0.06, 1.05, -0.108],
          desc: "Outer line, level with the Kidney shu. Low back pain, urinary and reproductive weakness; the Kidney's willpower (zhi)." },
        { code: "BL-53", name: "Baohuang", en: "Bladder's Vitals", pos: [0.055, 0.935, -0.098],
          desc: "On the buttock, level with the 2nd sacral foramen. Urinary retention and low back pain." },
        { code: "BL-54", name: "Zhibian", en: "Lowermost Edge", pos: [0.055, 0.89, -0.095],
          desc: "On the buttock, level with the 4th sacral foramen. A deep point for sciatica, low back pain and urinary disorders." },
        { code: "BL-38", name: "Fuxi", en: "Superficial Cleft", pos: [0.095, 0.55, -0.055],
          desc: "Above the outer knee crease. Cramping and numbness of the thigh and popliteal region." },
        { code: "BL-39", name: "Weiyang", en: "Bend Yang", pos: [0.095, 0.52, -0.05],
          desc: "Lower he-sea point of the Triple Energizer, at the outer knee crease. Regulates water: urinary difficulty and low back pain." },
        { pos: [0.082, 0.50, -0.045] }
      ]
    ]
  },
  {
    id: "KI",
    name: "Kidney",
    fullName: "Kidney Meridian of Foot Shaoyin",
    element: "Water",
    color: 0x5c6bc0,
    totalPoints: 27,
    bilateral: true,
    description:
      "Begins on the sole of the foot and ascends the inner leg and the front of the trunk close to the midline, ending under the clavicle. The Kidney stores essence (jing); its points treat low back pain, urinary and reproductive disorders, and issues of development and aging.",
    path: [
      { code: "KI-1", name: "Yongquan", en: "Gushing Spring", pos: [0.082, 0.005, 0.05],
        desc: "On the sole of the foot — the lowest point of the body. Descends excess yang and anchors the mind: hypertension, insomnia, agitation, and emergency loss of consciousness. Strongly grounding." },
      { code: "KI-2", name: "Rangu", en: "Blazing Valley", pos: [0.05, 0.045, 0.04],
        desc: "Ying-spring point on the inner arch. Clears deficiency heat: night sweats, dry throat and genital itching." },
      { code: "KI-3", name: "Taixi", en: "Great Ravine", pos: [0.048, 0.09, -0.04],
        desc: "Yuan-source point between the inner ankle bone and the Achilles tendon. Tonifies both Kidney yin and yang: low back pain, tinnitus, fatigue and reproductive weakness." },
      { code: "KI-4", name: "Dazhong", en: "Great Bell", pos: [0.05, 0.075, -0.05],
        desc: "Luo-connecting point at the inner heel. Fearfulness, low back pain and urinary difficulty." },
      { code: "KI-5", name: "Shuiquan", en: "Water Spring", pos: [0.05, 0.07, -0.03],
        desc: "Xi-cleft point below KI-3 on the inner heel. Acute menstrual pain and urinary difficulty." },
      { code: "KI-6", name: "Zhaohai", en: "Shining Sea", pos: [0.048, 0.065, -0.01],
        desc: "Below the inner ankle bone. Opens the Yin Motility vessel (Yin Qiao mai): insomnia, dry sore throat and menstrual irregularity." },
      { code: "KI-7", name: "Fuliu", en: "Returning Flow", pos: [0.05, 0.14, -0.045],
        desc: "Jing-river point two cun above the inner ankle. Regulates sweating (night sweats or absent sweating) and treats edema." },
      { code: "KI-8", name: "Jiaoxin", en: "Intersection Reach", pos: [0.048, 0.14, -0.028],
        desc: "In front of KI-7 above the inner ankle. Menstrual irregularity and uterine bleeding." },
      { code: "KI-9", name: "Zhubin", en: "Guest House", pos: [0.05, 0.22, -0.04],
        desc: "Xi-cleft point of the Yin Linking vessel, on the inner calf. Calms the mind: anxiety and agitation." },
      { code: "KI-10", name: "Yingu", en: "Yin Valley", pos: [0.05, 0.50, -0.03],
        desc: "He-sea point at the inner end of the knee crease. Treats knee pain and urinary and genital disorders." },
      { pos: [0.035, 0.72, 0.0] },
      { pos: [0.025, 0.90, 0.05] },
      { code: "KI-11", name: "Henggu", en: "Pubic Bone", pos: [0.012, 0.945, 0.08],
        desc: "At the upper border of the pubic bone, beside the midline. Urinary and genital disorders." },
      { code: "KI-12", name: "Dahe", en: "Great Manifestation", pos: [0.012, 0.965, 0.09],
        desc: "On the lower abdomen beside the midline. Genital and reproductive disorders." },
      { code: "KI-13", name: "Qixue", en: "Qi Hole", pos: [0.012, 0.985, 0.10],
        desc: "Level with CV-4, half a cun beside the midline. Menstrual irregularity and infertility." },
      { code: "KI-14", name: "Siman", en: "Fourfold Fullness", pos: [0.012, 1.005, 0.11],
        desc: "On the lower abdomen. Abdominal distension, menstrual pain and edema." },
      { code: "KI-15", name: "Zhongzhu", en: "Central Flow", pos: [0.012, 1.02, 0.115],
        desc: "Below the level of the navel beside the midline. Constipation and menstrual irregularity." },
      { code: "KI-16", name: "Huangshu", en: "Vitals Shu", pos: [0.012, 1.035, 0.12],
        desc: "Half a cun beside the navel. Abdominal pain, constipation and dry vomiting." },
      { code: "KI-17", name: "Shangqu", en: "Shang Bend", pos: [0.012, 1.06, 0.115],
        desc: "On the upper abdomen beside the midline. Abdominal pain and constipation." },
      { code: "KI-18", name: "Shiguan", en: "Stone Pass", pos: [0.012, 1.09, 0.112],
        desc: "On the upper abdomen. Abdominal pain, vomiting and constipation." },
      { code: "KI-19", name: "Yindu", en: "Yin Metropolis", pos: [0.012, 1.12, 0.11],
        desc: "On the upper abdomen level with CV-12. Epigastric pain, abdominal distension." },
      { code: "KI-20", name: "Futonggu", en: "Abdomen Connecting Valley", pos: [0.012, 1.15, 0.105],
        desc: "On the upper abdomen below the ribcage. Abdominal pain, vomiting and indigestion." },
      { code: "KI-21", name: "Youmen", en: "Dark Gate", pos: [0.012, 1.18, 0.10],
        desc: "At the upper abdomen beside the midline. Epigastric pain, vomiting and morning sickness. Needle with care." },
      { code: "KI-22", name: "Bulang", en: "Corridor Walk", pos: [0.03, 1.24, 0.09],
        desc: "In the 5th intercostal space beside the sternum. Cough, wheezing and chest fullness." },
      { code: "KI-23", name: "Shenfeng", en: "Spirit Seal", pos: [0.03, 1.275, 0.09],
        desc: "In the 4th intercostal space beside the sternum. Cough, chest oppression and breast pain." },
      { code: "KI-24", name: "Lingxu", en: "Spirit Ruins", pos: [0.03, 1.31, 0.088],
        desc: "In the 3rd intercostal space beside the sternum. Cough, chest pain and breast swelling." },
      { code: "KI-25", name: "Shencang", en: "Spirit Storehouse", pos: [0.03, 1.345, 0.085],
        desc: "In the 2nd intercostal space beside the sternum. Cough, wheezing and chest pain." },
      { code: "KI-26", name: "Yuzhong", en: "Lively Center", pos: [0.033, 1.385, 0.075],
        desc: "In the 1st intercostal space beside the sternum. Cough, wheezing and chest fullness." },
      { code: "KI-27", name: "Shufu", en: "Shu Mansion", pos: [0.035, 1.42, 0.06],
        desc: "In the depression below the clavicle, beside the midline. The last point of the meridian; used for cough, asthma and chest oppression." }
    ]
  },
  {
    id: "PC",
    name: "Pericardium",
    fullName: "Pericardium Meridian of Hand Jueyin",
    element: "Fire",
    color: 0xf06292,
    totalPoints: 9,
    bilateral: true,
    description:
      "The 'heart protector'. It emerges beside the nipple and runs down the middle of the inner arm to the tip of the middle finger. Its points treat nausea, palpitations, anxiety and oppression of the chest.",
    path: [
      { code: "PC-1", name: "Tianchi", en: "Celestial Pool", pos: [0.115, 1.265, 0.075],
        desc: "One cun beside the nipple. The first point of the meridian; used for chest oppression and rib-side pain." },
      { code: "PC-2", name: "Tianquan", en: "Celestial Spring", pos: [0.19, 1.30, -0.02],
        desc: "On the biceps two cun below the front armpit fold. Chest pain, cough and inner arm pain." },
      { code: "PC-3", name: "Quze", en: "Marsh at the Bend", pos: [0.235, 1.165, -0.02],
        desc: "He-sea point at the middle of the elbow crease, on the ulnar side of the biceps tendon. Clears heat from the blood, and treats nausea, vomiting and elbow pain." },
      { code: "PC-4", name: "Ximen", en: "Cleft Gate", pos: [0.288, 0.995, -0.02],
        desc: "Xi-cleft point on the middle of the forearm. Acute heart pain, palpitations and coughing blood." },
      { code: "PC-5", name: "Jianshi", en: "Intermediary Messenger", pos: [0.298, 0.96, -0.02],
        desc: "Jing-river point three cun above the wrist crease. Resolves phlegm affecting the heart: palpitations, mental disorders and malaria-like fevers." },
      { code: "PC-6", name: "Neiguan", en: "Inner Pass", pos: [0.305, 0.94, -0.022],
        desc: "Luo-connecting point, three finger-widths above the wrist crease. World-famous for nausea, vomiting and motion sickness; also treats anxiety, palpitations, insomnia and chest pain. Opens the Yin Linking vessel (Yin Wei mai)." },
      { code: "PC-7", name: "Daling", en: "Great Mound", pos: [0.32, 0.905, -0.025],
        desc: "Yuan-source point at the middle of the wrist crease. Calms the spirit: anxiety, palpitations and mouth ulcers; also carpal tunnel pain." },
      { code: "PC-8", name: "Laogong", en: "Palace of Toil", pos: [0.35, 0.80, -0.015],
        desc: "Ying-spring point at the center of the palm, where the middle finger falls when a fist is made. Clears heart heat: mouth ulcers, agitation and sweaty palms." },
      { code: "PC-9", name: "Zhongchong", en: "Central Rushing", pos: [0.377, 0.725, -0.045],
        desc: "Jing-well point at the tip of the middle finger. An emergency point for fainting, heat stroke and loss of consciousness." }
    ]
  },
  {
    id: "TE",
    name: "Triple Energizer",
    fullName: "Triple Energizer (San Jiao) Meridian of Hand Shaoyang",
    element: "Fire",
    color: 0xffa726,
    totalPoints: 23,
    bilateral: true,
    description:
      "Also called San Jiao or Triple Burner. It runs from the ring finger up the back of the arm, over the shoulder and around the ear to the outer eyebrow. It regulates the body's water passages and treats ear disorders and temporal headaches.",
    path: [
      { code: "TE-1", name: "Guanchong", en: "Passage Rushing", pos: [0.35, 0.735, -0.06],
        desc: "Jing-well point at the ulnar corner of the ring fingernail. Used for fever, sore throat and irritability." },
      { code: "TE-2", name: "Yemen", en: "Fluid Gate", pos: [0.347, 0.77, -0.065],
        desc: "Ying-spring point between the ring and little fingers. Sore throat, malaria-like fever and hand pain." },
      { code: "TE-3", name: "Zhongzhu", en: "Central Islet", pos: [0.34, 0.81, -0.068],
        desc: "Shu-stream point on the back of the hand between the 4th and 5th metacarpals. A key point for tinnitus, deafness, temporal headache and finger stiffness." },
      { code: "TE-4", name: "Yangchi", en: "Yang Pool", pos: [0.328, 0.895, -0.075],
        desc: "Yuan-source point at the center of the back of the wrist. Treats wrist pain and, classically, thirst and diabetes-like disorders." },
      { code: "TE-5", name: "Waiguan", en: "Outer Pass", pos: [0.315, 0.94, -0.078],
        desc: "Luo-connecting point, three finger-widths above the back of the wrist — the mirror of PC-6. Opens the Yang Linking vessel (Yang Wei mai): common cold, temporal headache, ear disorders and arm pain." },
      { code: "TE-6", name: "Zhigou", en: "Branch Ditch", pos: [0.312, 0.962, -0.078],
        desc: "Jing-river point on the back of the forearm. The classic point for constipation; also rib-side pain." },
      { code: "TE-7", name: "Huizong", en: "Convergence and Gathering", pos: [0.303, 0.96, -0.078],
        desc: "Xi-cleft point beside TE-6. Acute ear pain, deafness and epilepsy." },
      { code: "TE-8", name: "Sanyangluo", en: "Three Yang Connection", pos: [0.30, 0.99, -0.078],
        desc: "Where the three arm yang channels connect, on the back of the forearm. Sudden loss of voice, deafness and arm pain." },
      { code: "TE-9", name: "Sidu", en: "Four Rivers", pos: [0.278, 1.06, -0.075],
        desc: "On the back of the forearm below the elbow. Sudden loss of voice, deafness and forearm pain." },
      { code: "TE-10", name: "Tianjing", en: "Celestial Well", pos: [0.24, 1.195, -0.08],
        desc: "He-sea point in the depression above the tip of the elbow. Resolves phlegm nodules; elbow pain and migraine." },
      { code: "TE-11", name: "Qinglengyuan", en: "Clear Cold Abyss", pos: [0.235, 1.23, -0.08],
        desc: "Above the elbow tip on the back of the arm. Shoulder and arm pain." },
      { code: "TE-12", name: "Xiaoluo", en: "Dispersing Riverbed", pos: [0.22, 1.28, -0.08],
        desc: "On the back of the upper arm. Headache, neck stiffness and arm pain." },
      { code: "TE-13", name: "Naohui", en: "Upper Arm Convergence", pos: [0.205, 1.35, -0.08],
        desc: "On the back of the upper arm below the shoulder. Shoulder and arm pain, goiter." },
      { code: "TE-14", name: "Jianliao", en: "Shoulder Bone Hole", pos: [0.19, 1.445, -0.06],
        desc: "In the depression at the back of the shoulder when the arm is raised. A principal local point for shoulder pain, used together with LI-15." },
      { code: "TE-15", name: "Tianliao", en: "Celestial Bone Hole", pos: [0.11, 1.47, -0.06],
        desc: "On the upper corner of the shoulder blade. Shoulder and neck pain and stiffness." },
      { code: "TE-16", name: "Tianyou", en: "Celestial Window", pos: [0.095, 1.555, -0.04],
        desc: "On the side of the neck below the mastoid. Headache, neck stiffness and blurred vision." },
      { code: "TE-17", name: "Yifeng", en: "Wind Screen", pos: [0.10, 1.60, -0.01],
        desc: "In the depression behind the earlobe. A key point for tinnitus, deafness, ear infections and facial paralysis." },
      { code: "TE-18", name: "Qimai", en: "Spasm Vessel", pos: [0.103, 1.625, -0.022],
        desc: "Behind the ear at the center of the mastoid. Tinnitus, headache and infantile convulsions." },
      { code: "TE-19", name: "Luxi", en: "Skull Rest", pos: [0.10, 1.65, -0.024],
        desc: "Behind the upper ear. Tinnitus, ear pain and headache." },
      { code: "TE-20", name: "Jiaosun", en: "Angle Vertex", pos: [0.098, 1.675, 0.0],
        desc: "Above the apex of the ear. Ear swelling, toothache and stiff neck." },
      { code: "TE-21", name: "Ermen", en: "Ear Gate", pos: [0.10, 1.645, 0.022],
        desc: "In front of the ear above SI-19. Tinnitus, deafness, ear discharge and toothache." },
      { code: "TE-22", name: "Erheliao", en: "Ear Harmony Bone Hole", pos: [0.095, 1.652, 0.042],
        desc: "In front of the upper ear at the hairline. Tinnitus, headache and jaw tension." },
      { code: "TE-23", name: "Sizhukong", en: "Silk Bamboo Hole", pos: [0.077, 1.663, 0.072],
        desc: "In the depression at the outer end of the eyebrow. The last point of the meridian; treats temporal headache, migraine and eye disorders." }
    ]
  },
  {
    id: "GB",
    name: "Gallbladder",
    fullName: "Gallbladder Meridian of Foot Shaoyang",
    element: "Wood",
    color: 0x66bb6a,
    totalPoints: 44,
    bilateral: true,
    description:
      "Zigzags across the side of the head, descends the side of the neck, trunk and leg, and ends at the fourth toe. Associated with decision-making and the sinews; its points treat migraine, sciatica and pain along the sides of the body.",
    path: [
      { code: "GB-1", name: "Tongziliao", en: "Pupil Bone Hole", pos: [0.077, 1.65, 0.075],
        desc: "At the outer corner of the eye. Treats eye disorders, temporal headache and pain around the eye." },
      { code: "GB-2", name: "Tinghui", en: "Auditory Convergence", pos: [0.10, 1.61, 0.015],
        desc: "In front of the ear below SI-19. Tinnitus, deafness, TMJ pain and toothache." },
      { code: "GB-3", name: "Shangguan", en: "Above the Joint", pos: [0.10, 1.64, 0.03],
        desc: "Above the zygomatic arch in front of the ear. Ear disorders, migraine and facial paralysis." },
      { code: "GB-4", name: "Hanyan", en: "Forehead Fullness", pos: [0.095, 1.69, 0.035],
        desc: "On the temple within the hairline. Migraine, dizziness and tinnitus." },
      { code: "GB-5", name: "Xuanlu", en: "Suspended Skull", pos: [0.10, 1.683, 0.025],
        desc: "On the temple. Migraine and pain of the outer eye corner." },
      { code: "GB-6", name: "Xuanli", en: "Suspended Tuft", pos: [0.103, 1.675, 0.015],
        desc: "On the temple above the ear. Migraine, tinnitus and facial swelling." },
      { code: "GB-7", name: "Qubin", en: "Temporal Hairline Curve", pos: [0.104, 1.66, 0.002],
        desc: "At the temple above the ear apex. Migraine and jaw stiffness." },
      { code: "GB-8", name: "Shuaigu", en: "Valley Lead", pos: [0.10, 1.71, -0.005],
        desc: "Above the apex of the ear. A classic point for one-sided (temporal) headache and migraine; also hangover." },
      { code: "GB-9", name: "Tianchong", en: "Celestial Rushing", pos: [0.095, 1.71, -0.03],
        desc: "Behind GB-8 above the ear. Headache, gum swelling and epilepsy." },
      { code: "GB-10", name: "Fubai", en: "Floating White", pos: [0.09, 1.68, -0.055],
        desc: "Behind the ear. Headache, tinnitus and neck pain." },
      { code: "GB-11", name: "Touqiaoyin", en: "Head Portal Yin", pos: [0.085, 1.645, -0.065],
        desc: "Behind the ear above the mastoid. Headache, tinnitus, ear pain and neck stiffness." },
      { code: "GB-12", name: "Wangu", en: "Completion Bone", pos: [0.08, 1.60, -0.06],
        desc: "In the depression behind the mastoid process. Headache, insomnia, neck stiffness and facial paralysis." },
      { code: "GB-13", name: "Benshen", en: "Root of the Spirit", pos: [0.07, 1.73, 0.05],
        desc: "On the forehead within the hairline, above the outer eye. Calms the spirit: epilepsy, anxiety and headache." },
      { code: "GB-14", name: "Yangbai", en: "Yang White", pos: [0.055, 1.69, 0.085],
        desc: "On the forehead, one cun above the middle of the eyebrow. Used for frontal headache, eye problems and facial paralysis." },
      { code: "GB-15", name: "Toulinqi", en: "Head Overlooking Tears", pos: [0.055, 1.755, 0.055],
        desc: "Above the pupil within the hairline. Headache, eye disorders and nasal congestion." },
      { code: "GB-16", name: "Muchuang", en: "Eye Window", pos: [0.055, 1.775, 0.03],
        desc: "On the scalp above the eye. Eye pain, blurred vision and headache." },
      { code: "GB-17", name: "Zhengying", en: "Upright Nutrition", pos: [0.055, 1.78, 0.0],
        desc: "On the top of the scalp. Migraine, dizziness and toothache." },
      { code: "GB-18", name: "Chengling", en: "Spirit Support", pos: [0.05, 1.765, -0.035],
        desc: "On the back of the scalp. Headache, nasal congestion and nosebleed." },
      { code: "GB-19", name: "Naokong", en: "Brain Hollow", pos: [0.05, 1.705, -0.08],
        desc: "On the occiput above GB-20. Headache, neck stiffness and dizziness." },
      { code: "GB-20", name: "Fengchi", en: "Wind Pool", pos: [0.05, 1.578, -0.06],
        desc: "In the hollow below the base of the skull, between the muscles. One of the most used points of the body: headache, dizziness, common cold, stiff neck, hypertension and eye disorders." },
      { code: "GB-21", name: "Jianjing", en: "Shoulder Well", pos: [0.13, 1.46, -0.04],
        desc: "At the highest point of the shoulder muscle. The classic point for shoulder and neck tension; also promotes labor and lactation. Contraindicated during pregnancy." },
      { code: "GB-22", name: "Yuanye", en: "Armpit Abyss", pos: [0.16, 1.30, -0.01],
        desc: "On the side of the chest below the armpit. Chest fullness and rib-side pain." },
      { code: "GB-23", name: "Zhejin", en: "Flank Sinews", pos: [0.155, 1.29, 0.015],
        desc: "In front of GB-22 on the side of the chest. Chest oppression, asthma and rib-side pain." },
      { code: "GB-24", name: "Riyue", en: "Sun and Moon", pos: [0.10, 1.17, 0.09],
        desc: "Front-mu (alarm) point of the Gallbladder, below the nipple in the 7th intercostal space. Rib-side pain, jaundice and bitter taste." },
      { code: "GB-25", name: "Jingmen", en: "Capital Gate", pos: [0.14, 1.10, -0.04],
        desc: "Front-mu (alarm) point of the Kidney, at the free end of the 12th rib. Low back pain, abdominal distension and urinary difficulty." },
      { code: "GB-26", name: "Daimai", en: "Girdling Vessel", pos: [0.145, 1.03, 0.03],
        desc: "On the side of the waist level with the navel, where the Belt vessel circles the body. Menstrual disorders, vaginal discharge and hip pain." },
      { code: "GB-27", name: "Wushu", en: "Fifth Pivot", pos: [0.12, 0.97, 0.06],
        desc: "In front of the hip bone. Lower abdominal pain, hernia and vaginal discharge." },
      { code: "GB-28", name: "Weidao", en: "Linking Path", pos: [0.115, 0.945, 0.065],
        desc: "Below GB-27 in front of the hip. Lower abdominal pain and hip pain." },
      { code: "GB-29", name: "Juliao", en: "Squatting Bone Hole", pos: [0.15, 0.93, 0.0],
        desc: "On the side of the hip. Hip and low back pain, leg weakness." },
      { code: "GB-30", name: "Huantiao", en: "Jumping Round", pos: [0.14, 0.90, -0.06],
        desc: "Deep in the buttock, over the hip joint. The major point for sciatica, hip pain and weakness of the lower limb." },
      { code: "GB-31", name: "Fengshi", en: "Wind Market", pos: [0.145, 0.67, 0.01],
        desc: "On the outer thigh where the middle finger reaches when standing. Sciatica, leg weakness and itching of the whole body." },
      { code: "GB-32", name: "Zhongdu", en: "Middle Ditch", pos: [0.145, 0.61, 0.01],
        desc: "On the outer thigh below GB-31. Sciatica and leg numbness." },
      { code: "GB-33", name: "Xiyangguan", en: "Knee Yang Joint", pos: [0.125, 0.545, 0.0],
        desc: "On the outer knee above the joint. Knee pain and contracture of the leg." },
      { code: "GB-34", name: "Yanglingquan", en: "Yang Mound Spring", pos: [0.12, 0.49, 0.01],
        desc: "He-sea point below the head of the fibula, and influential point of the sinews. Treats all tendon and muscle disorders, sciatica, knee pain and rib-side pain." },
      { code: "GB-35", name: "Yangjiao", en: "Yang Intersection", pos: [0.115, 0.31, -0.02],
        desc: "Xi-cleft point of the Yang Linking vessel, on the outer calf. Rib-side pain and leg pain." },
      { code: "GB-36", name: "Waiqiu", en: "Outer Hill", pos: [0.115, 0.31, 0.0],
        desc: "Xi-cleft point of the Gallbladder, on the outer calf. Acute neck pain and rib-side pain." },
      { code: "GB-37", name: "Guangming", en: "Bright Light", pos: [0.11, 0.26, 0.0],
        desc: "Luo-connecting point on the outer calf. A principal distal point for eye disorders: blurred vision and night blindness." },
      { code: "GB-38", name: "Yangfu", en: "Yang Assistance", pos: [0.108, 0.20, -0.005],
        desc: "Jing-river point above the outer ankle. Migraine, rib-side pain and pain along the whole channel." },
      { code: "GB-39", name: "Xuanzhong", en: "Suspended Bell", pos: [0.106, 0.17, -0.01],
        desc: "Influential point of marrow, three cun above the outer ankle. Neck stiffness, leg weakness, and prevention of stroke; nourishes marrow." },
      { code: "GB-40", name: "Qiuxu", en: "Hill Ruins", pos: [0.10, 0.08, 0.03],
        desc: "Yuan-source point in front of and below the outer ankle bone. Ankle sprain, rib-side pain and indecision." },
      { code: "GB-41", name: "Zulinqi", en: "Foot Overlooking Tears", pos: [0.105, 0.045, 0.11],
        desc: "On the top of the foot, between the 4th and 5th metatarsals. Opens the Belt vessel (Dai mai): migraine, rib-side pain, menstrual disorders and foot pain." },
      { code: "GB-42", name: "Diwuhui", en: "Earth Five Convergences", pos: [0.107, 0.04, 0.128],
        desc: "Between the 4th and 5th metatarsals in front of GB-41. Red painful eyes, tinnitus and foot pain." },
      { code: "GB-43", name: "Xiaxi", en: "Pinched Ravine", pos: [0.11, 0.03, 0.148],
        desc: "Ying-spring point between the 4th and 5th toes. Clears heat: migraine, tinnitus, dizziness and outer-eye pain." },
      { code: "GB-44", name: "Zuqiaoyin", en: "Foot Portal Yin", pos: [0.112, 0.018, 0.168],
        desc: "Jing-well point at the lateral corner of the 4th toenail. Migraine, eye pain, tinnitus and restless sleep." }
    ]
  },
  {
    id: "LR",
    name: "Liver",
    fullName: "Liver Meridian of Foot Jueyin",
    element: "Wood",
    color: 0x9ccc65,
    totalPoints: 14,
    bilateral: true,
    description:
      "Runs from the big toe up the inner leg, through the groin, ending below the ribs. The Liver ensures the smooth flow of qi throughout the body; its points treat stress, irritability, menstrual disorders and eye problems.",
    path: [
      { code: "LR-1", name: "Dadun", en: "Great Esteem", pos: [0.065, 0.012, 0.165],
        desc: "Jing-well point at the lateral corner of the big toenail. Used for hernia, urinary disorders and excessive uterine bleeding." },
      { code: "LR-2", name: "Xingjian", en: "Moving Between", pos: [0.07, 0.03, 0.14],
        desc: "Ying-spring point between the 1st and 2nd toes. Clears Liver fire: red eyes, irritability, headache and menstrual pain." },
      { code: "LR-3", name: "Taichong", en: "Great Rushing", pos: [0.072, 0.045, 0.115],
        desc: "Yuan-source point on the top of the foot, between the 1st and 2nd metatarsals. With LI-4 it forms the 'Four Gates' to move qi throughout the body: stress, irritability, headache, hypertension and menstrual disorders." },
      { code: "LR-4", name: "Zhongfeng", en: "Mound Center", pos: [0.055, 0.08, 0.01],
        desc: "Jing-river point in front of the inner ankle. Hernia, urinary difficulty and ankle pain." },
      { code: "LR-5", name: "Ligou", en: "Woodworm Canal", pos: [0.045, 0.28, -0.01],
        desc: "Luo-connecting point on the inner shin. Genital itching, urinary difficulty and menstrual irregularity." },
      { code: "LR-6", name: "Zhongdu", en: "Central Metropolis", pos: [0.045, 0.33, -0.01],
        desc: "Xi-cleft point on the inner shin. Acute hernia pain and uterine bleeding." },
      { code: "LR-7", name: "Xiguan", en: "Knee Joint", pos: [0.048, 0.49, -0.015],
        desc: "Below the inner knee behind SP-9. Knee pain and weakness." },
      { code: "LR-8", name: "Ququan", en: "Spring at the Bend", pos: [0.048, 0.525, -0.01],
        desc: "He-sea point at the inner end of the knee crease. Nourishes Liver blood and treats knee pain, urinary and gynecological disorders." },
      { code: "LR-9", name: "Yinbao", en: "Yin Wrapping", pos: [0.055, 0.65, 0.02],
        desc: "On the inner thigh above the knee. Menstrual irregularity and low back pain radiating to the abdomen." },
      { code: "LR-10", name: "Zuwuli", en: "Leg Five Miles", pos: [0.06, 0.83, 0.045],
        desc: "On the upper inner thigh. Urinary retention and genital disorders." },
      { code: "LR-11", name: "Yinlian", en: "Yin Corner", pos: [0.06, 0.87, 0.05],
        desc: "On the upper inner thigh below the groin. Menstrual irregularity and leg pain." },
      { code: "LR-12", name: "Jimai", en: "Urgent Pulse", pos: [0.05, 0.93, 0.055],
        desc: "At the groin beside the genitals, over the femoral pulse. Hernia and genital pain. Needle with care." },
      { code: "LR-13", name: "Zhangmen", en: "Camphorwood Gate", pos: [0.135, 1.06, 0.02],
        desc: "Front-mu (alarm) point of the Spleen and influential point of the zang organs, at the free end of the 11th rib. Abdominal distension, rib-side pain and digestive weakness." },
      { code: "LR-14", name: "Qimen", en: "Cycle Gate", pos: [0.095, 1.19, 0.09],
        desc: "Front-mu (alarm) point of the Liver, on the rib cage below the nipple. The last point of the meridian; treats rib-side pain, chest fullness and emotional constraint." }
    ]
  },
  {
    id: "CV",
    name: "Conception Vessel",
    fullName: "Conception Vessel (Ren Mai)",
    element: "Extraordinary",
    color: 0xba68c8,
    totalPoints: 24,
    bilateral: false,
    description:
      "The 'Sea of Yin' — an extraordinary vessel running up the front midline from the perineum to the chin. It governs the yin of the whole body; its points strongly influence the reproductive, digestive and respiratory systems.",
    path: [
      { code: "CV-1", name: "Huiyin", en: "Meeting of Yin", pos: [0, 0.895, 0.01],
        desc: "At the perineum — the meeting point of the Conception, Governing and Penetrating vessels. Used in emergencies (drowning, loss of consciousness) and for genital disorders." },
      { code: "CV-2", name: "Qugu", en: "Curved Bone", pos: [0, 0.93, 0.09],
        desc: "At the upper border of the pubic bone. Urinary and genital disorders." },
      { code: "CV-3", name: "Zhongji", en: "Central Pole", pos: [0, 0.95, 0.10],
        desc: "Front-mu (alarm) point of the Bladder, four cun below the navel. Treats urinary disorders and disorders of the reproductive system." },
      { code: "CV-4", name: "Guanyuan", en: "Origin Pass", pos: [0, 0.975, 0.11],
        desc: "Front-mu point of the Small Intestine, three cun below the navel. One of the great tonification points of the body (often with moxa): exhaustion, coldness, and weakness of the reproductive and urinary systems." },
      { code: "CV-5", name: "Shimen", en: "Stone Gate", pos: [0, 0.99, 0.115],
        desc: "Front-mu (alarm) point of the Triple Energizer, two cun below the navel. Edema, abdominal pain and menstrual disorders." },
      { code: "CV-6", name: "Qihai", en: "Sea of Qi", pos: [0, 1.005, 0.12],
        desc: "One and a half cun below the navel. Strongly tonifies qi: chronic fatigue, weak digestion, abdominal coldness and prolapse." },
      { code: "CV-7", name: "Yinjiao", en: "Yin Intersection", pos: [0, 1.02, 0.122],
        desc: "One cun below the navel. Menstrual irregularity and abdominal pain." },
      { code: "CV-8", name: "Shenque", en: "Spirit Gate Tower", pos: [0, 1.035, 0.125],
        desc: "The navel itself. Needling is forbidden; moxibustion (often on salt) is used for collapse, coldness, chronic diarrhea and revival of yang." },
      { code: "CV-9", name: "Shuifen", en: "Water Divide", pos: [0, 1.055, 0.122],
        desc: "One cun above the navel. Separates the clear from the turbid: edema and diarrhea." },
      { code: "CV-10", name: "Xiawan", en: "Lower Stomach Duct", pos: [0, 1.075, 0.12],
        desc: "Two cun above the navel. Food stagnation: fullness after eating and undigested food in the stools." },
      { code: "CV-11", name: "Jianli", en: "Interior Strengthening", pos: [0, 1.10, 0.118],
        desc: "Three cun above the navel. Epigastric pain, poor appetite and edema." },
      { code: "CV-12", name: "Zhongwan", en: "Central Stomach Duct", pos: [0, 1.13, 0.115],
        desc: "Front-mu point of the Stomach, midway between navel and sternum, and influential point of the fu organs. The central point for all digestive disorders: epigastric pain, bloating, nausea and poor appetite." },
      { code: "CV-13", name: "Shangwan", en: "Upper Stomach Duct", pos: [0, 1.16, 0.11],
        desc: "Five cun above the navel. Nausea, vomiting and epigastric pain." },
      { code: "CV-14", name: "Juque", en: "Great Tower Gate", pos: [0, 1.185, 0.105],
        desc: "Front-mu (alarm) point of the Heart, below the sternum. Palpitations, anxiety, chest pain and acid reflux." },
      { code: "CV-15", name: "Jiuwei", en: "Turtledove Tail", pos: [0, 1.21, 0.10],
        desc: "Below the tip of the sternum. Calms the spirit: anxiety, mania and chest pain. Needle obliquely." },
      { code: "CV-16", name: "Zhongting", en: "Central Courtyard", pos: [0, 1.24, 0.095],
        desc: "On the sternum at the 5th intercostal level. Chest fullness and difficulty swallowing." },
      { code: "CV-17", name: "Danzhong", en: "Chest Center", pos: [0, 1.27, 0.09],
        desc: "Front-mu point of the Pericardium, at the center of the sternum between the nipples, and influential point of qi. Treats chest tightness, breathlessness, palpitations, emotional constraint and breast disorders." },
      { code: "CV-18", name: "Yutang", en: "Jade Hall", pos: [0, 1.31, 0.088],
        desc: "On the sternum above CV-17. Cough, asthma and chest pain." },
      { code: "CV-19", name: "Zigong", en: "Purple Palace", pos: [0, 1.345, 0.085],
        desc: "On the sternum at the 2nd intercostal level. Cough, asthma and chest fullness." },
      { code: "CV-20", name: "Huagai", en: "Florid Canopy", pos: [0, 1.38, 0.08],
        desc: "On the sternum at the 1st intercostal level. Cough, asthma and rib-side pain." },
      { code: "CV-21", name: "Xuanji", en: "Jade Pivot", pos: [0, 1.41, 0.075],
        desc: "On the upper sternum below the notch. Cough, wheezing and throat obstruction." },
      { code: "CV-22", name: "Tiantu", en: "Celestial Chimney", pos: [0, 1.45, 0.06],
        desc: "In the notch above the sternum. A local point for cough, asthma, sore throat and the sensation of something stuck in the throat. Needle with care." },
      { code: "CV-23", name: "Lianquan", en: "Corner Spring", pos: [0, 1.545, 0.08],
        desc: "Above the Adam's apple, under the chin. Speech and swallowing disorders: post-stroke aphasia, excessive salivation." },
      { code: "CV-24", name: "Chengjiang", en: "Sauce Receptacle", pos: [0, 1.575, 0.10],
        desc: "In the depression below the lower lip. The last point of the vessel; treats facial paralysis, toothache and excessive salivation." }
    ]
  },
  {
    id: "GV",
    name: "Governing Vessel",
    fullName: "Governing Vessel (Du Mai)",
    element: "Extraordinary",
    color: 0x4dd0e1,
    totalPoints: 28,
    bilateral: false,
    description:
      "The 'Sea of Yang' — an extraordinary vessel running from the tailbone up the spine, over the top of the head and down to the upper lip. It governs all the yang meridians; its points treat spinal problems, fever and disorders of the mind.",
    path: [
      { code: "GV-1", name: "Changqiang", en: "Long Strong", pos: [0, 0.89, -0.06],
        desc: "Luo-connecting point between the tip of the coccyx and the anus. Hemorrhoids, rectal prolapse and coccyx pain." },
      { code: "GV-2", name: "Yaoshu", en: "Lumbar Shu", pos: [0, 0.94, -0.095],
        desc: "At the sacral hiatus. Low back stiffness and pain, hemorrhoids." },
      { code: "GV-3", name: "Yaoyangguan", en: "Lumbar Yang Pass", pos: [0, 1.00, -0.112],
        desc: "Below the 4th lumbar vertebra. Low back pain radiating to the legs, and weakness of the knees." },
      { code: "GV-4", name: "Mingmen", en: "Gate of Life", pos: [0, 1.06, -0.116],
        desc: "Below the 2nd lumbar vertebra, between the Kidneys. Warms and tonifies the yang of the whole body (often with moxa): cold low back pain, exhaustion, and weakness of the reproductive system." },
      { code: "GV-5", name: "Xuanshu", en: "Suspended Pivot", pos: [0, 1.10, -0.114],
        desc: "Below the 1st lumbar vertebra. Low back stiffness, diarrhea and indigestion." },
      { code: "GV-6", name: "Jizhong", en: "Spinal Center", pos: [0, 1.14, -0.11],
        desc: "Below the 11th thoracic vertebra. Jaundice, diarrhea and epilepsy." },
      { code: "GV-7", name: "Zhongshu", en: "Central Pivot", pos: [0, 1.17, -0.108],
        desc: "Below the 10th thoracic vertebra. Low back pain and epigastric pain." },
      { code: "GV-8", name: "Jinsuo", en: "Sinew Contraction", pos: [0, 1.20, -0.105],
        desc: "Below the 9th thoracic vertebra. Spasms, rigidity of the spine and epilepsy." },
      { code: "GV-9", name: "Zhiyang", en: "Reaching Yang", pos: [0, 1.23, -0.10],
        desc: "Below the 7th thoracic vertebra, at the level of the diaphragm. Jaundice, chest and back pain, cough." },
      { code: "GV-10", name: "Lingtai", en: "Spirit Tower", pos: [0, 1.27, -0.098],
        desc: "Below the 6th thoracic vertebra. Cough, asthma and back pain; classically for boils." },
      { code: "GV-11", name: "Shendao", en: "Spirit Path", pos: [0, 1.30, -0.095],
        desc: "Below the 5th thoracic vertebra, level with the Heart. Palpitations, poor memory and anxiety." },
      { code: "GV-12", name: "Shenzhu", en: "Body Pillar", pos: [0, 1.35, -0.09],
        desc: "Below the 3rd thoracic vertebra. Cough, asthma, back stiffness; a classical point for strengthening children." },
      { code: "GV-13", name: "Taodao", en: "Kiln Path", pos: [0, 1.42, -0.10],
        desc: "Below the 1st thoracic vertebra. Fever with chills, headache and stiff spine." },
      { code: "GV-14", name: "Dazhui", en: "Great Hammer", pos: [0, 1.49, -0.10],
        desc: "Below the 7th cervical vertebra — the meeting point of all yang meridians. Clears heat and releases the exterior: fever, common cold, stiff neck and malaria-like alternating chills and fever." },
      { code: "GV-15", name: "Yamen", en: "Gate of Muteness", pos: [0, 1.578, -0.068],
        desc: "At the midline of the nape, above the hairline. Speech disorders and neck stiffness. Needle with great care (no deep or upward needling)." },
      { code: "GV-16", name: "Fengfu", en: "Wind Mansion", pos: [0, 1.60, -0.072],
        desc: "In the hollow below the external occipital protuberance. Expels wind: headache, stiff neck, dizziness and sore throat. Needle with great care." },
      { code: "GV-17", name: "Naohu", en: "Brain's Door", pos: [0, 1.70, -0.092],
        desc: "On the occipital protuberance. Head heaviness, neck stiffness and dizziness." },
      { code: "GV-18", name: "Qiangjian", en: "Unyielding Space", pos: [0, 1.755, -0.07],
        desc: "On the back of the head above GV-17. Headache, neck stiffness and insomnia." },
      { code: "GV-19", name: "Houding", en: "Behind the Vertex", pos: [0, 1.79, -0.04],
        desc: "Behind the vertex of the head. Headache, vertigo and agitation." },
      { code: "GV-20", name: "Baihui", en: "Hundred Meetings", pos: [0, 1.80, 0.0],
        desc: "At the vertex — the crown of the head, where all yang converges. Raises sinking qi and calms the spirit: prolapse, dizziness, headache, poor memory and mental fog; a key point for mental clarity." },
      { code: "GV-21", name: "Qianding", en: "Before the Vertex", pos: [0, 1.795, 0.04],
        desc: "In front of the vertex. Headache at the top of the head, dizziness and nasal congestion." },
      { code: "GV-22", name: "Xinhui", en: "Fontanelle Meeting", pos: [0, 1.775, 0.075],
        desc: "At the anterior fontanelle. Headache, dizziness and nasal congestion. Forbidden in infants." },
      { code: "GV-23", name: "Shangxing", en: "Upper Star", pos: [0, 1.755, 0.09],
        desc: "One cun within the front hairline. The classic point for nasal congestion and nosebleed; also frontal headache." },
      { code: "GV-24", name: "Shenting", en: "Courtyard of the Spirit", pos: [0, 1.735, 0.10],
        desc: "At the front hairline on the midline. Calms the spirit: insomnia, anxiety, frontal headache." },
      { code: "GV-25", name: "Suliao", en: "White Bone Hole", pos: [0, 1.615, 0.115],
        desc: "At the tip of the nose. Nasal congestion, nosebleed and (in emergencies) collapse with shock." },
      { code: "GV-26", name: "Shuigou (Renzhong)", en: "Water Trough", pos: [0, 1.596, 0.105],
        desc: "In the philtrum, below the nose. The foremost emergency revival point: fainting, shock and collapse; also used for acute lumbar sprain." },
      { code: "GV-27", name: "Duiduan", en: "Extremity of the Mouth", pos: [0, 1.585, 0.108],
        desc: "At the tip of the upper lip. Gum swelling, nasal congestion and mania." },
      { code: "GV-28", name: "Yinjiao", en: "Gum Intersection", pos: [0, 1.578, 0.10],
        desc: "Inside the upper lip at the junction of gum and frenulum. Gum diseases and acute lumbar pain. The final point of the vessel." }
    ]
  }
];
